_wandb:
    value:
        cli_version: 0.23.1
        e:
            vr0qly0060vvzjelxz9hh44s6rtusb0h:
                args:
                    - --batch_size=64
                    - --epochs=15
                    - --learning_rate=0.06678528914501357
                codePath: s2_CNN_MNIST/src/s2_cnn_mnist/train.py
                codePathLocal: src/s2_cnn_mnist/train.py
                cpu_count: 6
                cpu_count_logical: 12
                disk:
                    /:
                        total: "473139372032"
                        used: "195277078528"
                email: s214722@dtu.dk
                executable: /home/clara/DTU/9. semester/ml_ops/s2_CNN_MNIST/.venv/bin/python
                git:
                    commit: 87ec3566ba155a887d17debee7baff2c6bc9ffd0
                host: clara-framework
                memory:
                    total: "16028950528"
                os: Linux-6.18.3-arch1-1-x86_64-with-glibc2.42
                program: /home/clara/DTU/9. semester/ml_ops/s2_CNN_MNIST/src/s2_cnn_mnist/train.py
                python: CPython 3.12.12
                root: /home/clara/DTU/9. semester/ml_ops/s2_CNN_MNIST
                startedAt: "2026-01-10T11:32:48.711092Z"
                writerId: vr0qly0060vvzjelxz9hh44s6rtusb0h
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 14
                - 16
            "4": 3.12.12
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
architecture:
    value: CNN
batch_size:
    value: 64
dataset:
    value: MNIST
epochs:
    value: 15
learning_rate:
    value: 0.06678528914501357
