_wandb:
    value:
        cli_version: 0.23.1
        e:
            p7gvdgb9y1pylj6ft6x6aajtotz3dlmr:
                args:
                    - --batch_size=64
                    - --epochs=5
                    - --learning_rate=0.08142283589662432
                codePath: s2_CNN_MNIST/src/s2_cnn_mnist/train.py
                codePathLocal: train.py
                email: s214722@dtu.dk
                executable: /home/clara/DTU/9. semester/ml_ops/s2_CNN_MNIST/.venv/bin/python
                git:
                    commit: 87ec3566ba155a887d17debee7baff2c6bc9ffd0
                host: clara-framework
                os: Linux-6.18.3-arch1-1-x86_64-with-glibc2.42
                program: /home/clara/DTU/9. semester/ml_ops/s2_CNN_MNIST/src/s2_cnn_mnist/train.py
                python: CPython 3.12.12
                root: /home/clara/DTU/9. semester/ml_ops/s2_CNN_MNIST/src/s2_cnn_mnist
                startedAt: "2026-01-10T09:47:52.330703Z"
                writerId: p7gvdgb9y1pylj6ft6x6aajtotz3dlmr
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 14
                - 16
            "4": 3.12.12
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
architecture:
    value: CNN
batch_size:
    value: 64
dataset:
    value: MNIST
epochs:
    value: 5
learning_rate:
    value: 0.08142283589662432
