_wandb:
    value:
        cli_version: 0.23.1
        e:
            b48u7nirxay08kpz37c3x4267xrwhx07:
                codePath: s2_CNN_MNIST/src/s2_cnn_mnist/train.py
                codePathLocal: src/s2_cnn_mnist/train.py
                email: s214722@dtu.dk
                executable: /home/clara/DTU/9. semester/ml_ops/.venv/bin/python
                git:
                    commit: 87ec3566ba155a887d17debee7baff2c6bc9ffd0
                host: clara-framework
                os: Linux-6.18.3-arch1-1-x86_64-with-glibc2.42
                program: /home/clara/DTU/9. semester/ml_ops/s2_CNN_MNIST/src/s2_cnn_mnist/train.py
                python: CPython 3.12.12
                root: /home/clara/DTU/9. semester/ml_ops/s2_CNN_MNIST
                startedAt: "2026-01-08T13:06:58.052475Z"
                writerId: b48u7nirxay08kpz37c3x4267xrwhx07
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 16
            "4": 3.12.12
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
architecture:
    value: CNN
dataset:
    value: MNIST
epochs:
    value: 10
learning_rate:
    value: 0.001
